"""empty message

Revision ID: 054191c4ee1f
Revises: 0a8462397dcf
Create Date: 2018-08-16 13:24:37.619334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054191c4ee1f'
down_revision = '0a8462397dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_email'), 'email', ['email'], unique=True)
    op.create_index(op.f('ix_email_token'), 'email', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_token'), table_name='email')
    op.drop_index(op.f('ix_email_email'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
